### ISSUE TITLE
Long line in template_jobs/includes/someprogram.sas does not get sent in entirety via VSCode extension

### ISSUE THREAD

**Issue by TeMeta** [sasjs/template_jobs#14]
```
58        data _null_;
WARNING: Truncated record
59          putlog "It doesn't matter if there are extra apostrophes";
60          putlog "lines can also be really looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
WARNING: End-of-file encountered in string
ERROR: Expected column, formatted, list or named PUT statement
61        run;
```

I'm not sure if this is intended to work or not, but flagging for awareness.

I'm using a SASjs server and the file works with the long line removed.

**Comment by allanbowe** [comment]
Thanks for raising. This extra long line is deliberately in the repo as an example of an exception / problem when checking against `sasjs lint`.  

So to that end it's working as expected (to demonstrate the need for a lint when running SAS).

The error itself can be avoided by setting `options lrecl=10000;` eg as follows:

<img width="1721" alt="image" src="https://user-images.githubusercontent.com/4420615/192152677-3ed9bc65-7f7d-4963-8b5c-4d2c27ad533e.png">


The problem is also visible when running directly in SASjs Studio or with the SASjs CLI, ie, it's a SAS session issue..
